name: icon_cleaner
version: 1.0.8
description: A Dart CLI tool that automatically removes emoji and non-ASCII characters from Flutter project Dart files. Useful for cleaning up code copied from AI tools like ChatGPT.
homepage: https://github.com/AnjanaMurugan/icon_cleaner

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.4.2
  path: ^1.9.0

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0

executables:
  icon_cleaner: icon_cleaner